### ISSUE TITLE
Error: Missing type field on Linter Response

### ISSUE THREAD

**Issue by gnestor** [nmn/linter-flow-plus#10]
```
Error: Missing type field on Linter Response
    at /Users/grant/.atom/packages/linter/lib/validate.coffee:30:19
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (/Users/grant/.atom/packages/linter/lib/validate.coffee:26:14)
    at MessageRegistry.set (/Users/grant/.atom/packages/linter/lib/message-registry.js:36:16)
    at /Users/grant/.atom/packages/linter/lib/linter.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/grant/.atom/packages/linter/lib/linter-registry.js:66:26
```

I get this error on every buffer change (whenever I type something). Here's an example flow response and as you can see, the type field is `undefined`:

```
{
  "text": "react-native-silent-switch Required module not found",
  "filePath": "/Users/grant/Sites/whammy/react.whammy/Whammy.js",
  "range": [
    [
      27,
      25
    ],
    [
      27,
      53
    ]
  ],
  "trace": [
    {
      "type": "Trace",
      "text": "Required module not found",
      "filePath": "",
      "range": [
        [
          -1,
          0
        ],
        [
          -1,
          0
        ]
      ]
    }
  ],
  "type": undefined
}
```

I'm using flow-bin@0.28

**Comment by gnestor** [comment]
Also getting with with flow-bin@0.27

**Comment by nmn** [comment]
This package is deprecated. Please using `linter-flow` instead.

**Comment by gnestor** [comment]
K thanks

**Comment by tonyxiao** [comment]
Oh how come it's deprecated?

**Comment by nmn** [comment]
I was made a contributor on the linter-flow package. So in order to minimize fragmentation, I deprecated this package, and started doing all my development on `linter-flow`
